theme: jekyll-theme-slate
title: Admission Intelligence
description: A data driven architecture and decision services implementation for improving preventable admission rates. Future of Healthcare Hackathon
